
site_name: brainlife Documentation
site_author: 'The people of brainlife.io'
site_url: https://brainlife.io/docs

#
# Repository
repo_name: 'brainlife/docs'
repo_url: 'https://github.com/brainlife/docs'

copyright: 'Copyright &copy; 2017 - 2020 brainlife.io'

theme:
  name: 'material'
  language: 'en'
  favicon: '/img/favicon.ico'
  palette:
    primary: 'light blue'
  custom_dir: overrides

nav:
  - Home: index.md

  - Using brainlife:
    - Getting Started: user/started.md
    - Projects: user/project.md
    - Datatypes: user/datatypes.md
    - Archive: user/archive.md
    - Processes: user/process.md
    - Pipelines: user/pipeline.md
    - Group Analysis: user/groupanalysis.md
    - Publications: user/publication.md
    - Datasets : user/datasets.md
    - Failure: user/failure.md

  - Tutorials: 
    - Introduction: tutorial/introduction-to-brainlife.md
    - Anatomy: tutorial/t1w-preprocessing.md
    - FMRI Preprocessing: tutorial/fmri-preprocessing-tutorial.md
    - PRF Mapping: tutorial/prf-mapping.md
    - DWI Preprocessing : tutorial/diffusion-preprocessing.md
    - DWI Tractometry: tutorial/diffusion-tractography.md
    - FMRI networks: tutorial/networkneuroscience-functional.md
    - DMRI networks: tutorial/networkneuroscience-structural.md
    - Network Neuroscience: tutorial/networkneuroscience.md
    - Cortex Tissue Mapping: tutorial/cortex-tissue-mapping.md

  - Using CLI:
    - Installation: cli/install.md
    - Uploading Data: cli/upload.md
    - Running Apps: cli/app.md
    - Downloading Data: cli/download.md
    - Update Data: cli/update.md
    - Group Analysis: cli/group.md

  - Developing Apps: 
    - Introduction: apps/introduction.md
    - HelloWorld: apps/helloworld.md
    - Registering App: apps/register.md
    - Containerizing App: apps/container.md
    - Versioning Tips: apps/versioning.md
    - Custom Hooks: apps/customhooks.md
    - product.json: apps/product.md

  - Compute Resources: 
    - Registering Resource: resources/register.md

  - Technical:
    - Architecture: technical/arthitecture.md
    - APIs: technical/api.md

  - Careers: careers/jobs.md

  - Contact: contact.md
  - Privacy Policy: privacy.md
  - AUP: aup.md
  - Media / Branding: media.md

extra:
  disqus: 'brain-life'
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/BrainLifeio'
    - icon: fontawesome/brands/github
      link: 'https://github.com/brainlife'

extra_css:
    - css/narrow.css

markdown_extensions:
  - admonition
  - toc:
        permalink: True
  - fontawesome_markdown
  - attr_list
  - pymdownx.highlight:
        linenums: true
  - pymdownx.superfences

